version: '3'

services:
    container1:
        hostname: container1
        restart: always
        image: danjellz/http-server
        expose:
            - "8001"
        volumes:
            - ./proj1:/public
        command: "http-server . -p 8001"
        networks:
            - app-network

    container2:
        hostname: container2
        restart: always
        image: danjellz/http-server
        expose:
            - "8002"
        volumes:
            - ./proj2:/public
        command: "http-server . -p 8002"
        networks:
            - app-network
        
    container_nginx:
        build:
            context: .
            dockerfile: docker/Dockerfile_nginx
        ports:
            - 80:80
            - 443:443
        networks:
            - app-network
        volumes:
            - "./projnginx/certs/:/etc/ssl/certs/"
            - "./projnginx/private/:/etc/ssl/private/"
            - "./projnginx/snippets/:/etc/nginx/snippets/"
        depends_on:
            - container1
            - container2

networks:
    app-network:
        driver: bridge  